fix issue #3 bosh compilation should not require internet access (maven repo)

diff --git a/packages/iaas_exporter_pkg/packaging b/packages/iaas_exporter_pkg/packaging
--- a/packages/iaas_exporter_pkg/packaging
+++ b/packages/iaas_exporter_pkg/packaging
@@ -1,37 +1,12 @@
-set -e -x
-export JAVA_HOME=/var/vcap/packages/openjdk/jre
-export PATH=$JAVA_HOME/bin:$PATH
-export NAME_MODULE_JAVA=prometheus-iaas-tenant-exporter
 
-cd ${NAME_MODULE_JAVA}
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
 
-function extract_host_port() {
-sed -e 's`https\?://\([^/]*\).*`\1`i'
-}
+# Detect # of CPUs so make jobs can be parallelized
+CPUS=$(grep -c ^processor /proc/cpuinfo)
+ # Available variables
+# $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
+# $BOSH_INSTALL_TARGET - where you copy/install files to be included in package
+export HOME=/var/vcap
 
-set +u
-#########################################
-## Declare proxy if http_proxy env exist
-#########################################
-declare -a JAVA_OPTS
-if [ -n "$http_proxy" ]; then
-JAVA_OPTS+=(-Dhttp.proxyHost=$(echo "$http_proxy" | extract_host_port | cut -d: -f1))
-JAVA_OPTS+=(-Dhttp.proxyPort=$(echo "$http_proxy" | extract_host_port | cut -d: -f2))
-fi
-if [ -n "$https_proxy" ]; then
-JAVA_OPTS+=(-Dhttps.proxyHost=$(echo "$https_proxy" | extract_host_port | cut -d: -f1))
-JAVA_OPTS+=(-Dhttps.proxyPort=$(echo "$https_proxy" | extract_host_port | cut -d: -f2))
-fi
-
-
-export MAVEN_OPTS="${JAVA_OPTS[@]}"
-#########################################
-# do the compilation
-# assert that build final name is set to NAME_MODULE_JAVA
-#########################################
-set -u
-cp /var/vcap/packages/vcloud/* ./libs/.
-./mvnw -X clean install -DskipTests=true
-
-
-mv target/exporter.jar ${BOSH_INSTALL_TARGET}
+cp -r ${BOSH_COMPILE_TARGET}/exporter.jar ${BOSH_INSTALL_TARGET}/exporter.jar
